name: Run Playwright API Call

on:
  workflow_dispatch:   # Trigger manually

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Playwright Run API
        run: |
          curl --location 'https://beta8.moontechnolabs.com/tms-one-api/api/v1/playwright/run-tests-ciCD?id=273&email=anand@moontechnolabs.com
